---
name: "Meilisearch"
guid: "7ead92dc-95aa-47c3-87bb-8b9b8e312238"
version: '1.0.0'
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "A Meilisearch Plugin for Jellyfin"
imageUrl: https://raw.githubusercontent.com/meilisearch/meilisearch/refs/heads/main/assets/meilisearch-logo-dark.svg
description: >
  This is a plugin that try to use Meilisearch to speedup the search of jellyfin.
  Inspired by Jellysearch
category: "General"
owner: "a.sac."
artifacts:
  - "Jellyfin.Plugin.Meilisearch.dll"
  - "Jellyfin.Plugin.Meilisearch.pdb"
  - "Meilisearch.dll"
  - "Microsoft.IdentityModel.Abstractions.dll"
  - "Microsoft.IdentityModel.JsonWebTokens.dll"
  - "Microsoft.IdentityModel.Logging.dll"
  - "Microsoft.IdentityModel.Tokens.dll"
  - "System.IdentityModel.Tokens.Jwt.dll"
changelog: changelog